REPLACE_FLAT_MODEL_VALUES = {'MODEL A-MAISONETTE':'MAISONETTE',
                            '3GEN': 'MULTI GENERATION',
                            'MULTI-GENERATION': 'MULTI GENERATION',
                            'IMPROVED-MAISONETTE':'MAISONETTE',
                            'EXECUTIVE MAISONETTE': 'MAISONETTE',
                            'PREMIUM MAISONETTE':'MAISONETTE',
                            'PREMIUM APARTMENT LOFT': 'APARTMENT',
                            'PREMIUM APARTMENT': 'APARTMENT',
                            'TYPE S1':'SPECIAL',
                            'TYPE S2':'SPECIAL',
                            'TERRACE':'SPECIAL',
                            'ADJOINED FLAT':'SPECIAL',
                            'DBSS': 'SPECIAL',
                            'MODEL A2': 'MODEL A',
                            'SIMPLIFIED': 'MODEL A',
                            'IMPROVED': 'STANDARD',
                            '2-ROOM': 'STANDARD'}